@Library('library')_

pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/franckbond007/newjava.git")
                }
            }
        }
        stage('ContinuousBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }
        }
         stage('ContinuousDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeployment("http://172.31.20.47:8080", "testapp")
                }
            }
        }
         stage('ContinuousTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.newGit('https://github.com/franckbond007/FunctionalTesting.git')
                    cicd.newSelenium('/var/lib/jenkins/workspace/pipelinewithlibraries/')
                }
            }
        }
        stage('ContinuousDeploy_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("http://172.31.15.28:8080", "prodapp")
                    
                }
            }
        }
    }
}
